### PR TITLE
Return true in save! method

### PR DESCRIPTION
**Pull request by njaeggi**

### CODE REVIEW

**Review by hunchr — APPROVED** [review]
nice, jetzt wird das kind immer gespeichert

**Comment by njaeggi** [comment]
We don't want to always return true, when generate_invoice is executed but fails to create invoice (for whatever reason) save! should return false and not just always true @hunchr

**Comment by hunchr** [comment]
doesn't save! raise an error? so the rest won't be executed anyway

**Comment by njaeggi** [comment]
that's true since we use create! for both mailing lists and invoice... maybe there is a case where the invoice job fails to enqueue, that's what maybe should return false... I don't really know if that case is even possible tho :thinking:

**Comment by hunchr** [comment]
the return value of `generate_invoice` is irrelevant anyway because `exclude_from_mailing_list` will be returned

**Pull request merged**
